//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string AttendanceId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Date { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public Nullable<double> WorkHours { get; set; }
        public Nullable<double> Wage { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
